In [ ]:
#numpy assignment

In [2]:
#1
!pip install numpy
import numpy as np

In [9]:
#2
import numpy as np
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,S

In [21]:
#3
x = np.zeros(10)
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
#4
n = np.zeros((3,3))
print("%d bytes" % (n.size * n.itemsize))

72 bytes


In [12]:
#5
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [13]:
#6
Z=np.zeros(10)
Z[4]=1
print(Z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
#7
Z=np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
#8
Z = np.arange(50)
x = Z[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [20]:
#9
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
#10
nz=np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4], dtype=int64),)


In [24]:
#11
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#12
Z=np.random.random((3,3,3))
print(Z)

[[[0.13159158 0.83608985 0.12410216]
  [0.47413573 0.81552508 0.60568939]
  [0.25179227 0.50768857 0.5378301 ]]

 [[0.14881053 0.66924297 0.35984936]
  [0.75414777 0.98861062 0.11735868]
  [0.03741966 0.28933334 0.19521998]]

 [[0.36843296 0.74192261 0.18837419]
  [0.03524305 0.65243286 0.40121858]
  [0.04735131 0.85153231 0.56722628]]]


In [26]:
#13
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()
print(Zmin, Zmax)

0.012099604975868705 0.9999027476012888


In [27]:
#14
Z=np.random.random(30)
m = Z.mean()
print(m)

0.4947279534191195


In [32]:
#15
Z=np.ones((10,10))
Z[1:-1,1:-1]=0

In [33]:
#16
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [38]:
#17
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [39]:
#18
Z=np.diag(1+np.arange(4),k=-1)
print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [40]:
#19
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [41]:
#20
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [42]:
#21
Z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [43]:
#22
Z=np.random.random((5,5))
Zmax,Zmin=Z.max(),Z.min()
Z=(Z-Zmin)/(Zmax-Zmin)
print(Z)

[[0.82036655 0.53304026 0.01210031 0.         0.11979874]
 [0.55079487 0.14238067 0.26067204 0.44124169 0.64600997]
 [0.81106389 0.99395546 0.58305712 0.46096734 1.        ]
 [0.20855977 0.98753677 0.84149409 0.31397284 0.20360144]
 [0.52829676 0.01695286 0.84776927 0.10405383 0.84804342]]


In [44]:
#23
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])

C:\Users\hp\AppData\Local\Temp\ipykernel_15008\2668473121.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),


In [45]:
#24
Z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [48]:
#25
Z=np.arange(11)
Z[(3<Z)&(Z<=8)]*=-1

In [49]:
#26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [53]:
#27
print(Z**Z)#Integers to negative integer powers are not allowed.
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)#he truth value of an array with more than one element is ambiguous

[  0   1   2   4   0   0   0   0   0 256 512]
[False False False False  True  True  True  True  True False False]
[ 0. +0.j  0. +1.j  0. +2.j  0. +3.j -0. -4.j -0. -5.j -0. -6.j -0. -7.j
 -0. -8.j  0. +9.j  0.+10.j]
[ 0.  1.  2.  3. -4. -5. -6. -7. -8.  9. 10.]


In [54]:
#28
np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)

C:\Users\hp\AppData\Local\Temp\ipykernel_15008\1798798899.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\hp\AppData\Local\Temp\ipykernel_15008\1798798899.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

In [55]:
#29
Z=np.random.uniform(-10,+10,10)
print(np.trunc(Z+np.copysign(0.5,Z)))

[ 2.  6.  6.  0.  5.  4.  1.  4. -9.  2.]


In [56]:
#30
ar1 = np.array([0, 1, 2, 3, 4, 7, 9])
ar2 = [1, 3, 5, 6, 9]
print(np.intersect1d(ar1, ar2))

[1 3 9]


In [58]:
#31
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0


In [59]:
#32
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [60]:
#33
import numpy as np
  
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(today)
print(yesterday)
print(tomorrow)

2022-09-19
2022-09-18
2022-09-20


In [61]:
#34
month = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(month)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [62]:
#35
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [63]:
#36
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(np.ceil(Z))
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


[8. 1. 2. 2. 4. 2. 9. 7. 9. 6.]
[ 9.  2.  3.  3.  5.  3. 10.  8. 10.  7.]
[8. 1. 2. 2. 4. 2. 9. 7. 9. 6.]
[8 1 2 2 4 2 9 7 9 6]
[8. 1. 2. 2. 4. 2. 9. 7. 9. 6.]


In [64]:
#37
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [65]:
#38
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [66]:
#39
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [67]:
#40
random_vector = np.random.random(10)
random_vector.sort()
print(random_vector)

[0.17535266 0.39881208 0.50891928 0.52987757 0.53683053 0.6440116
 0.72901442 0.814514   0.85073542 0.96824789]


In [68]:
#41
Z = np.arange(10)
np.add.reduce(Z)

45

In [70]:
#42
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [71]:
#43
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [72]:
#44
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.34454022 0.99869856 0.64665969 0.9062941  0.81356879 1.0849811
 0.92685254 0.89103567 0.18391907 1.21873777]
[0.75685443 0.19793704 1.04244354 0.43947771 1.45321691 1.11209789
 0.92553931 0.92386772 0.66617029 0.75547777]


In [73]:
#45
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.58523863 0.89475937 0.26908607 0.6246766  0.02744384 0.
 0.60535327 0.16881266 0.02696124 0.48589769]


In [74]:
#46
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [75]:
#47
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [76]:
#48

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [77]:
#49
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [78]:
#50
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

93


In [3]:
#51
a= np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\hp\AppData\Local\Temp\ipykernel_9120\1037912971.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a= np.zeros(10, [ ('position', [ ('x', float, 1),


In [4]:
#52
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((100,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.46103467 0.47760575 ... 0.55983053 0.58652279 0.86285606]
 [0.46103467 0.         0.32657711 ... 0.32540387 0.19001627 0.86809844]
 [0.47760575 0.32657711 0.         ... 0.09439866 0.25288107 0.54170923]
 ...
 [0.55983053 0.32540387 0.09439866 ... 0.         0.19846614 0.56040932]
 [0.58652279 0.19001627 0.25288107 ... 0.19846614 0.         0.75726985]
 [0.86285606 0.86809844 0.54170923 ... 0.56040932 0.75726985 0.        ]]
[[0.         0.62078918 0.17741467 ... 0.42971405 0.40549561 0.49484689]
 [0.62078918 0.         0.46806798 ... 0.20311504 0.58548311 0.48763772]
 [0.17741467 0.46806798 0.         ... 0.298978   0.4478166  0.48490964]
 ...
 [0.42971405 0.20311504 0.298978   ... 0.         0.40593177 0.3416612 ]
 [0.40549561 0.58548311 0.4478166  ... 0.40593177 0.         0.14977551]
 [0.49484689 0.48763772 0.48490964 ... 0.3416612  0.14977551 0.        ]]


In [5]:
#53
a= np.arange(10, dtype=np.float32)
A= a.astype(np.int32, copy=False)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [6]:
#54
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\hp\AppData\Local\Temp\ipykernel_9120\1984016776.py:9: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


In [7]:
#55
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [8]:
#56
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [9]:
#57
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
#58
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.25085424  0.23386432 -0.07092582  0.24640394 -0.36895876 -0.50619919
  -0.04107679 -0.06294027  0.33011224 -0.01113389]
 [ 0.2879955  -0.26933138 -0.31158648  0.18585923 -0.17760648 -0.17833855
   0.36719619 -0.14538778 -0.13165326  0.37285301]
 [-0.19041943  0.42447737  0.26959089 -0.35322051  0.36399491  0.27083085
  -0.16250116 -0.42290667 -0.00436061 -0.19548564]
 [ 0.10874154 -0.21587832  0.36845972 -0.23184331  0.41410262 -0.17387478
   0.37842435 -0.04260116 -0.32571119 -0.27981947]
 [-0.0912114   0.33315891  0.27042424  0.28284724 -0.18357149 -0.25340738
  -0.2360461   0.09668594  0.22127557 -0.44015554]]


In [11]:
#59
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 5 0]
 [4 1 1]
 [8 3 6]]
[[4 1 1]
 [8 3 6]
 [8 5 0]]


In [12]:
#60
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [13]:
#61
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.42997142074847516


In [14]:
#62
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [15]:
#63
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [16]:
#64
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 5. 1. 3. 5. 4. 2. 2. 3.]


In [17]:
#65
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [19]:
#66
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


In [20]:
#67
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[64 58 58 54]
 [65 44 52 56]
 [27 69 41 44]]
[[64 58 58 54]
 [65 44 52 56]
 [27 69 41 44]]


In [22]:
#68
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.3947678  0.47329106 0.59412846 0.5401994  0.34464005 0.45859833
 0.59540224 0.49080996 0.48575194 0.34586583]
0    0.394768
1    0.473291
2    0.594128
3    0.540199
4    0.344640
5    0.458598
6    0.595402
7    0.490810
8    0.485752
9    0.345866
dtype: float64


In [23]:
#69
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([0.90339408, 1.49737523, 1.24182873, 1.66812499, 1.33749885])

In [24]:
#70
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [25]:
#71
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [26]:
#72
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [27]:
#73
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 57) ( 2, 79) (10, 28) (10, 86) (18, 26) (18, 36) (21, 50) (21, 51)
 (21, 69) (21, 79) (22, 66) (22, 79) (24, 42) (24, 71) (26, 36) (28, 86)
 (31, 31) (31, 39) (31, 66) (31, 77) (39, 77) (42, 71) (47, 82) (47, 83)
 (50, 79) (51, 69) (57, 79) (66, 79) (82, 83)]


In [28]:
#74
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [30]:
#75
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [31]:
#76
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [32]:
#77
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


array([-0.59100383, -0.77406263,  0.5465008 ,  0.44205839, -0.84704984,
       -0.6913822 ,  0.6771906 ,  0.37917068, -0.22578377,  0.348776  ,
        0.07162704,  0.638384  ,  0.22494731,  0.79203804, -0.04490332,
       -0.60641618, -0.07403626,  0.22056894,  0.6356037 , -0.36509051,
        0.34235253, -0.45764142, -0.30506969,  0.44503351, -0.18392663,
       -0.86354543, -0.16543446, -0.02738622,  0.8539932 , -0.19009503,
        0.25313115, -0.68049931, -0.17205875, -0.63536691,  0.61740717,
        0.23438485,  0.02985124,  0.78560593,  0.07060547,  0.00749154,
       -0.25493235, -0.96359251,  0.78798227,  0.30377364,  0.24221635,
        0.66049749,  0.74285488, -0.96899308,  0.40908578,  0.99742377,
        0.39467218,  0.15025118, -0.22102873, -0.3114352 , -0.22177864,
        0.99962608, -0.71507797,  0.46992561,  0.84155801,  0.07252374,
        0.98328773,  0.0501663 , -0.19179565,  0.33120461, -0.57588776,
        0.66688456, -0.53673356,  0.27609077, -0.55661887, -0.67

In [33]:
#78

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 9.02025534  1.19462899 12.9646088  14.47005932  0.28471883 10.28386191
  1.94091508 10.48479315 14.49672626  2.84207895]


In [34]:
#79

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.53558695  5.48279865  7.60040156  9.9034824   3.21643986  1.02512274
   1.00582712  0.91988986  2.56061686 10.83053829]
 [ 4.68703772  2.83716994  5.40167432 11.29567624  1.30868717  0.52821774
   1.56969912  3.29286931  1.49327076 11.54809211]
 [ 1.46502344  3.47195161  9.06003886 13.01065955  5.06375663  2.0240068
   1.13759445  3.35993114  0.62208032 14.04067525]
 [ 3.59740406  1.15873098  3.37643969 14.24639662  0.20815188  3.64761907
   5.53663504  7.1403491   1.10024115 13.73466828]
 [ 0.48800928  1.84377335  9.71789123 15.1835834   6.00764124  4.18014535
   2.84201061  5.22910673  2.80218737 16.19390906]
 [ 2.40090949  4.04450531  2.31637334 16.64079907  0.87965392  6.14062968
   8.42538675 10.00076062  3.27812733 15.65638195]
 [ 1.14747527  2.57473306  4.68702862 16.61945848  1.39047211  5.96350153
   7.06277816  8.91605658  3.55560057 16.23583816]
 [ 1.9157223   7.46443252  0.14337798 18.87844177  2.64091994  8.54799239
  11.7944229  13.20428291  5.16476972 17.15355413]
 

In [35]:
#80
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 0 3 4 6 7 7 4 8 5]
 [6 0 7 3 6 2 1 8 0 9]
 [0 2 5 4 8 6 6 0 4 3]
 [2 5 5 7 8 7 0 9 8 7]
 [3 4 5 9 9 0 3 2 3 1]
 [4 5 6 6 1 9 2 6 0 0]
 [9 7 1 2 3 1 9 8 1 6]
 [3 1 1 4 7 0 7 7 5 2]
 [1 1 6 8 7 6 7 0 4 1]
 [0 7 1 0 1 0 8 9 1 9]]
[[0 0 0 0 0]
 [0 7 0 3 4]
 [0 6 0 7 3]
 [0 0 2 5 4]
 [0 2 5 5 7]]


C:\Users\hp\AppData\Local\Temp\ipykernel_9120\3288931093.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [37]:
#81
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [38]:
#82
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [39]:
#83
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


In [40]:
#84
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 2 2]
   [2 3 4]
   [4 2 3]]

  [[2 2 0]
   [3 4 3]
   [2 3 4]]

  [[2 0 0]
   [4 3 0]
   [3 4 3]]

  [[0 0 3]
   [3 0 3]
   [4 3 1]]

  [[0 3 1]
   [0 3 4]
   [3 1 3]]

  [[3 1 3]
   [3 4 2]
   [1 3 0]]

  [[1 3 0]
   [4 2 2]
   [3 0 2]]

  [[3 0 2]
   [2 2 2]
   [0 2 1]]]


 [[[2 3 4]
   [4 2 3]
   [1 4 4]]

  [[3 4 3]
   [2 3 4]
   [4 4 4]]

  [[4 3 0]
   [3 4 3]
   [4 4 3]]

  [[3 0 3]
   [4 3 1]
   [4 3 0]]

  [[0 3 4]
   [3 1 3]
   [3 0 4]]

  [[3 4 2]
   [1 3 0]
   [0 4 0]]

  [[4 2 2]
   [3 0 2]
   [4 0 0]]

  [[2 2 2]
   [0 2 1]
   [0 0 2]]]


 [[[4 2 3]
   [1 4 4]
   [2 0 0]]

  [[2 3 4]
   [4 4 4]
   [0 0 0]]

  [[3 4 3]
   [4 4 3]
   [0 0 0]]

  [[4 3 1]
   [4 3 0]
   [0 0 3]]

  [[3 1 3]
   [3 0 4]
   [0 3 1]]

  [[1 3 0]
   [0 4 0]
   [3 1 2]]

  [[3 0 2]
   [4 0 0]
   [1 2 3]]

  [[0 2 1]
   [0 0 2]
   [2 3 3]]]


 [[[1 4 4]
   [2 0 0]
   [3 2 4]]

  [[4 4 4]
   [0 0 0]
   [2 4 4]]

  [[4 4 3]
   [0 0 0]
   [4 4 1]]

  [[4 3 0]
   [0 0 3]
   [4 1 0]]

  [[3 0 4]
   

In [41]:
#85
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


[[ 8  9 10  7  7]
 [ 9  3  4  2  7]
 [10  4  0 42 10]
 [ 7  2 42  5  3]
 [ 7  7 10  3  5]]


In [42]:
#86
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [43]:
#87

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [44]:
#88
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [45]:
#89
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [47]:
#90
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [48]:
#91
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [49]:
#92
# Commented out IPython magic to ensure Python compatibility.
x = np.random.rand(int(5e7))

# %timeit np.power(x,3)
# %timeit x*x*x
# %timeit np.einsum('i,i,i->i',x,x,x)

In [50]:
#93
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 4 5 6]


In [51]:
#94
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 1 0]
 [3 4 0]
 [3 2 4]
 [4 4 0]
 [1 1 2]
 [2 3 4]
 [3 4 0]
 [1 1 1]
 [4 2 4]
 [3 2 2]]
[[3 1 0]
 [3 4 0]
 [3 2 4]
 [4 4 0]
 [1 1 2]
 [2 3 4]
 [3 4 0]
 [4 2 4]
 [3 2 2]]
[[3 1 0]
 [3 4 0]
 [3 2 4]
 [4 4 0]
 [1 1 2]
 [2 3 4]
 [3 4 0]
 [4 2 4]
 [3 2 2]]


In [52]:
#95

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [53]:
#96
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)



[[0 0 0]
 [0 0 1]
 [1 1 0]
 [1 1 1]]


In [54]:
#97
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)


array([[0.16094096, 0.66652132, 0.66599123, 0.47917592, 0.60606937,
        0.03149268, 0.48395651, 0.31799217, 0.18913348, 0.02691538],
       [0.16529717, 0.68456217, 0.68401773, 0.49214586, 0.62247395,
        0.0323451 , 0.49705585, 0.32659932, 0.19425278, 0.02764391],
       [0.114289  , 0.47331679, 0.47294035, 0.3402772 , 0.43038804,
        0.0223639 , 0.34367204, 0.22581578, 0.13430936, 0.01911342],
       [0.1404112 , 0.58149932, 0.58103685, 0.41805185, 0.52875867,
        0.02747545, 0.42222263, 0.27742883, 0.16500746, 0.02348203],
       [0.17589337, 0.72844528, 0.72786594, 0.52369433, 0.66237696,
        0.03441855, 0.52891907, 0.34753561, 0.20670515, 0.02941599],
       [0.20422521, 0.84577883, 0.84510618, 0.60804784, 0.76906863,
        0.03996248, 0.61411415, 0.40351454, 0.23999996, 0.03415414],
       [0.06346253, 0.26282388, 0.26261486, 0.18894951, 0.23898636,
        0.01241825, 0.1908346 , 0.12539124, 0.07457945, 0.01061332],
       [0.09496272, 0.39327886, 0.3929660

In [55]:
#98
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [56]:
#99
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [57]:
#100
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.21879898  0.19714396]
